services:
  dev-vm:
    build: .
    container_name: elastic-dev-vm
    privileged: true
    ports:
      - "3500:22"
    volumes:
      - E:\DOCKER_FILES\elastic-dev-vm\home:/root
    restart: unless-stopped
