name: Collect metrics
description: Collects workflow metrics for deployments
enabled: true
consts:
  DEPLOYMENTS_INDEX: deployed-previews
  METRICS_INDEX: workflow_metrics
triggers:
  - type: manual
  - type: scheduled
    with:
      every: 1m
steps:
  - name: create_workflow_metrics_collector_index
    type: elasticsearch.request
    on-failure:
      continue: true
    with:
      method: POST
      path: /{{ consts.METRICS_INDEX }}
      body:
        mappings:
          dynamic: false
          properties:
            id:
              type: keyword
            "@timestamp":
              type: date
            finishedAt:
              type: date
            status:
              type: keyword
            workflowId:
              type: keyword
            spaceId:
              type: keyword
            metric:
              type: keyword
            value:
              type: double
            unit:
              type: keyword
            tags:
              type: keyword
            project:
              type: keyword

  - name: fetch_deployments
    type: elasticsearch.request
    with:
      method: GET
      path: /{{consts.DEPLOYMENTS_INDEX}}/_search

  - name: foreach_deployment
    type: foreach
    foreach: "${{ steps.fetch_deployments.output.hits.hits | map: '_source' }}"
    steps:
      - name: kibana_auth_var
        type: data.set
        with:
          Authorization: "Basic {{foreach.item.es_user | append: ':' | append: foreach.item.es_password | base64_encode}}"
      - name: fetch_executions
        type: http
        with:
          url: "{{ foreach.item.es_internal_url }}/.workflows-executions/_search"
          method: POST
          headers:
            Authorization: "{{ steps.kibana_auth_var.output.Authorization }}"
            Content-Type: application/json
          body:
            size: 10000
            _source:
              - id
              - workflowId
              - status
              - startedAt
              - createdAt
              - finishedAt
              - duration
            query:
              bool:
                must:
                  - range:
                      createdAt:
                        gte: now-2m

      - name: build_metrics
        type: code.javascript
        with:
          code: |
            var executions = {{ steps.fetch_executions.output.data.hits.hits | map: "_source" | json }};
            var project = '{{foreach.item.container_name}}';

            function buildItem({ execution, metricName, value }) {
              var id = `${metricName}_${execution.id}`;

              if (typeof value !== 'number') {
                throw new Error(`${metricName}:${typeof value} metric unit isn't supported.`);
              }

              return {
                id,
                metric: `workflow.${metricName}`,
                value,
                unit: 'int',
                ['@timestamp']: execution.createdAt,
                finishedAt: execution.finishedAt || null,
                status: execution.status,
                workflowId: execution.workflowId,
                spaceId: execution.spaceId,
                project
              };
            }

            var result = [];
            while (executions.length) {
              var execution = executions.splice(0, 1)[0];
              var { createdAt, startedAt, finishedAt, duration } = execution;
              result.push(buildItem({ execution, metricName: 'count', value: 1 }));
              if (duration != null)
                result.push(buildItem({ execution, metricName: 'duration', value: duration }));
              if (createdAt && startedAt)
                result.push(buildItem({ execution, metricName: 'queueTime',
                  value: new Date(startedAt).getTime() - new Date(createdAt).getTime() }));
              if (createdAt && finishedAt)
                result.push(buildItem({ execution, metricName: 'e2eLatency',
                  value: new Date(finishedAt).getTime() - new Date(createdAt).getTime() }));
            }
            return result;

      - name: prepare_bulk_body
        type: code.javascript
        with:
          code: |
            var metrics = {{ steps.build_metrics.output | json }};
            var index = "{{ consts.METRICS_INDEX }}";
            return metrics.flatMap(m => [
              JSON.stringify({ index: { _index: index, _id: m.id } }),
              JSON.stringify(m)
            ]).join('\n') + '\n';

      - name: bulk_index_metrics
        type: elasticsearch.request
        with:
          method: POST
          path: /_bulk
          headers:
            Content-Type: application/x-ndjson
          body: '${{ steps.prepare_bulk_body.output }}'
