name: Collect metrics
description: Collects workflow metrics for deployments
enabled: true
consts:
  DEPLOYMENTS_INDEX: deployed-previews
  METRICS_INDEX: workflow_metrics
triggers:
  - type: manual
  - type: scheduled
    with:
      every: 1m
steps:
  - name: create_workflow_metrics_collector_index
    type: elasticsearch.request
    on-failure:
      continue: true
    with:
      method: PUT
      path: /{{ consts.METRICS_INDEX }}
      body:
        mappings:
          dynamic: false
          properties:
            id:
              type: keyword
            "@timestamp":
              type: date
            workflowId:
              type: keyword
            spaceId:
              type: keyword
            metric:
              type: keyword
            value:
              type: double
            unit:
              type: keyword
            tags:
              type: keyword
            project:
              type: keyword

  - name: fetch_deployments
    type: elasticsearch.request
    with:
      method: GET
      path: /{{consts.DEPLOYMENTS_INDEX}}/_search

  - name: foreach_deployment
    type: foreach
    foreach: "${{ steps.fetch_deployments.output.hits.hits | map: '_source' }}"
    steps:
      - name: kibana_auth_var
        type: data.set
        with:
          Authorization: "Basic {{foreach.item.es_user | append: ':' | append: foreach.item.es_password | base64_encode}}"

      - name: fetch_executions
        type: http
        with:
          url: "{{ foreach.item.es_internal_url }}/.workflows-executions/_search"
          method: POST
          headers:
            Authorization: "{{ steps.kibana_auth_var.output.Authorization }}"
            Content-Type: application/json
          body:
            size: 5000
            _source:
              - id
              - workflowId
              - status
              - startedAt
              - createdAt
              - finishedAt
              - duration
            query:
              bool:
                must:
                  - range:
                      createdAt:
                        gte: now-2m

      - name: convert_to_chunks
        type: code.javascript
        with:
          code: |
            var executions = {{ steps.fetch_executions.output.data.hits.hits | map: '_source' | json }};
            var chunks = [];
            while(executions.length) {
              if (!chunks.length || (chunks.at(-1) && chunks.at(-1).length >= 500)) {
                chunks.push([]);
              }

              chunks.at(-1).push(executions.pop());
            }
            return chunks;

      - name: handle_batches
        type: foreach
        foreach: "${{ steps.convert_to_chunks.output }}"
        steps:
          - name: build_metrics
            type: code.javascript
            with:
              code: |
                var executions = {{ foreach.item | json }};
                var project = '{{steps.foreach_deployment.item.container_name}}';
                var result = [];

                function insert({ execution, metricName, value }) {
                  var id = `${metricName}_${execution.id}`;

                  if (typeof value !== 'number') {
                    throw new Error(`${metricName}:${typeof value} metric unit isn't supported.`);
                  }

                  result.push({
                    id,
                    metric: `workflowExecution.${metricName}`,
                    value,
                    unit: 'int',
                    ['@timestamp']: execution.createdAt,
                    finishedAt: execution.finishedAt || null,
                    status: execution.status,
                    workflowId: execution.workflowId,
                    spaceId: execution.spaceId,
                    project
                  });
                }

                while (executions.length) {
                  var execution = executions.pop();
                  if (!execution) continue;
                  var { createdAt, startedAt, finishedAt, duration } = execution;
                  insert({ execution, metricName: 'count', value: 1 });
                  if (duration != null)
                    insert({ execution, metricName: 'duration', value: duration });
                  if (createdAt && startedAt)
                    insert({ execution, metricName: 'queueTime',
                      value: new Date(startedAt).getTime() - new Date(createdAt).getTime() });
                  if (createdAt && finishedAt)
                    insert({ execution, metricName: 'e2eLatency',
                      value: new Date(finishedAt).getTime() - new Date(createdAt).getTime() });
                }
                return result;

          - name: prepare_bulk_body
            type: code.javascript
            with:
              code: |
                var metrics = {{ steps.build_metrics.output | slice: 0, 5000 | json }};
                var index = "{{ consts.METRICS_INDEX }}";
                var body = '';
                while (metrics.length) {
                  var m = metrics.pop();
                  body += JSON.stringify({ index: { _index: index, _id: m.id } }) + '\n';
                  body += JSON.stringify(m) + '\n';
                }
                return body;

          - name: bulk_index_metrics
            type: elasticsearch.request
            with:
              method: POST
              path: /_bulk
              headers:
                Content-Type: application/x-ndjson
              body: '${{ steps.prepare_bulk_body.output }}'
